<% project_name = 'Full-Stack-Project-Rails-API' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: Full-Stack-Project-Rails-API_development

test:
  <<: *default
  database: Full-Stack-Project-Rails-API_test
